### ISSUE TITLE
UTF-8 encoding.

### ISSUE THREAD

**Issue by RolandoCartagena** [f00b4r/nusoap#101]
When I am creating the server and add `$server->soap_defencoding = 'UTF-8'; `

The XML is always generated with encoding="ISO-8859-1".

Inside the nusoap class the change was made:
     //var $soap_defencoding = 'ISO-8859-1';
     var $soap_defencoding = 'UTF-8';

The XML is always generated with encoding="ISO-8859-1".

In line 5643 it was found `$xml = '<?xml version="1.0" encoding="ISO-8859-1"?>';`

was replaced by `$xml = '<?xml version="1.0" encoding="' . $this->soap_defencoding . '"?>';`

The XML is already generated correctly

`<?xml version="1.0" encoding="UTF-8"?>`

**Comment by haeussler-pharma4u** [comment]
I created a pull request that fixes this issue, without changing the default soap_defencoding: https://github.com/f00b4r/nusoap/pull/114

**Comment by marcovtwout** [comment]
@f3l1x Since https://github.com/f00b4r/nusoap/pull/114 is merged this issue can be closed.

**Comment by f3l1x** [comment]
Thank you @marcovtwout
