### ISSUE TITLE
Type error in get_class with php 8.*

### ISSUE THREAD

**Issue by la-magra** [f00b4r/nusoap#95]
I'm opening this issue for visibility.

As succinctly explained in this commit comment https://github.com/f00b4r/nusoap/commit/687c73dce97eec5a907687ee896b93d92c929210#commitcomment-101952700
by @Nielslinde

`get_class()` is throwing type errors in php8.*

**Comment by santyzu13** [comment]
It's working if I download it from github, but It's not working if I use **composer require econea/nusoap**. It's not updated on composer repository.

Thanks.

**Comment by la-magra** [comment]
Seems fixed with release v0.9.15.
